name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Validate Maven project
        run: |
          mvn validate
          if [ $? -ne 0 ]; then
            echo "Maven validation failed"
            exit 1
          fi

      - name: Build with Maven
        run: |
          mvn clean package
          if [ $? -ne 0 ]; then
            echo "Maven build failed"
            exit 1
          fi

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: |
          ./mvnw install
          if [ $? -ne 0 ]; then
            echo "Maven install failed"
            exit 1
          fi

      - name: Run tests
        run: |
          ./mvnw test
          if [ $? -ne 0 ]; then
            echo "Maven test failed"
            exit 1
          fi