name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code-quality-check:
    name: Code Quality Check (Checkstyle)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: ./mvnw install

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check

      - name: Handle Checkstyle Errors
        if: failure()
        run: |
          echo "Checkstyle found issues in the code. Please fix the errors."
          echo "Checkstyle Report:"
          cat target/checkstyle-result.xml || echo "No report available"
          exit 1
