name: Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code Quality Check (Checkstyle)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: ./mvnw install

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check

      - name: Handle errors
        if: failure()
        run: |
          echo "Error occurred during code quality check"
          echo "Please check the logs for more information"